  workflows: 
    macos-build:
      name: macOS Build
      instance_type: mac_pro
      environment:
        groups:
          - prod 
        node: 16.14.0

      scripts:
        - name: Injecting env vars
          script: echo "REACT_APP_API_KEY=$REACT_APP_API_KEY" >> .env
        - name: Injecting env vars (2)
          script: echo "GH_TOKEN=$GH_TOKEN" >> .env
        - name: Installing packages
          script: yarn install
        - name: Building Applications - React
          script: yarn build
        - name: Building Application - Electron
          script: yarn electron-builder -m --publish always -c.extraMetadata.main=build/electron.js 

      artifacts:
        - out/make/*.dmg
        
      publishing:
        scripts:
          -name: github 
          script: |
          gh release create "v1.0.1"